### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by alexanderkhitev** [zenangst/Blueprints#144]
Hey! Does this framework have any performance specifications? How many cells we can use/fetch at once? Thanks!

**Comment by zenangst** [comment]
Hey @alexanderkhitev, we haven't done any "scientific" measurements but we have had performance as one of our cornerstones when developing the framework. It should be robust because it leverages from binary search when it comes to letting the UI know which cells should be drawn on screen. Probably not the answer that you want but it would probably be a good idea just to try it out to see if "the shoe fits".

Note that performance may vary depending on the layout. Vertical and horizontal should be quite performant as is.

**Comment by alexanderkhitev** [comment]
Hey @zenangst ! Thank you for a detailed answer!

**Comment by zenangst** [comment]
@alexanderkhitev you are most welcome! 😎
